### ISSUE TITLE
For Monday, 7/20: Webpack

### ISSUE THREAD

**Issue by NicoleLatifi** [NicoleLatifi/refactor-tractor#19]
In Refactor Tractor spec, go through the Webpack section and look at all links.

- [x] Naomi
- [x] Nicole
- [x] Aaron

(If you are the last one to check your box, please close the issue. Thank You!)

**Comment by Abdeboskey** [comment]
Ok, that article that is linked is very dry and wordy, and I almost fell asleep twice reading it just now. But, the Conclusion section was a succinct way of summarizing all the things in the article (even if I don't quite understand them yet).
