### ISSUE TITLE
ToDo for Saturday: Read repos and specs individually.

### ISSUE THREAD

**Issue by NicoleLatifi** [NicoleLatifi/refactor-tractor#9]
- make note of anything that is in the spec that is not already completed in the project we've been assigned (i.e. iteration, UI, code)

* [Fitlit Spec!](https://frontend.turing.io/projects/fitlit.html)

* [Refactor Tractor Spec!](https://frontend.turing.io/projects/module-2/refactor-tractor.html)

**Comment by Abdeboskey** [comment]
this is broken down into more specific issues ( #15 & #16 )
